{
 "title": "品质分析系统",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "各不良原因时间占比(%)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT sum(extract(epoch FROM (release_time - start_time)))/60 as value,now() as time,'品质原因1' as metric\r\nfrom andon.error_log\r\nwhere tag_type_sub_name='quality_error' and error_type_detail_name='品质原因1' and to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')"
    },
    {
     "rawSql": "SELECT sum(extract(epoch FROM (release_time - start_time)))/60 as value,now() as time,'品质原因2' as metric\r\nfrom andon.error_log\r\nwhere tag_type_sub_name='quality_error' and error_type_detail_name='品质原因2' and to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')"
    },
    {
     "rawSql": "SELECT sum(extract(epoch FROM (release_time - start_time)))/60 as value,now() as time,'品质原因3' as metric\r\nfrom andon.error_log\r\nwhere tag_type_sub_name='quality_error' and error_type_detail_name='品质原因3' and to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')"
    },
    {
     "rawSql": "SELECT sum(extract(epoch FROM (release_time - start_time)))/60 as value,now() as time,'其他' as metric\nfrom andon.error_log\nwhere tag_type_sub_name='quality_error' and error_type_detail_name='其他' and to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')"
    }
   ]
  },
  { "title": "各不良原因次数统计", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 7, "y": 0 }, "content": "# title" },
  {
   "title": "品质不良时长分析",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT sum(cost_time) as value, to_date(mytime,'yyyy-MM-dd') as time\r\nfrom \r\n(SELECT cost_time,to_char(start_time,'yyyy-MM-dd') as mytime\r\n  from andon.error_log \r\n  where tag_type_sub_name='quality_error' and to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')) res\r\n  group by mytime\r\n  order by mytime"
    }
   ]
  },
  {
   "title": "品质原因1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(extract(epoch FROM (release_time - start_time)))/60 as value,now() as time,'品质原因1' as metric\r\nfrom andon.error_log\r\nwhere tag_type_sub_name='quality_error' and error_type_detail_name='品质原因1' and to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "品质原因2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(extract(epoch FROM (release_time - start_time)))/60 as value,now() as time,'品质原因2' as metric\r\nfrom andon.error_log\r\nwhere tag_type_sub_name='quality_error' and error_type_detail_name='品质原因2' and to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "品质原因3",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(extract(epoch FROM (release_time - start_time)))/60 as value,now() as time,'品质原因3' as metric\r\nfrom andon.error_log\r\nwhere tag_type_sub_name='quality_error' and error_type_detail_name='品质原因3' and to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "其他",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(extract(epoch FROM (release_time - start_time)))/60 as value,now() as time,'其他' as metric\r\nfrom andon.error_log\r\nwhere tag_type_sub_name='品质异常' and error_type_detail_name='其他' and to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "品质不良详情",
   "type": "advantech-datatable-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT machine_name as \"站位\",\r\n  to_char(start_time,'yyyy-MM-dd hh24:mi:ss') as \"触发时间\",to_char(release_time,'yyyy-MM-dd hh24:mi:ss') as \"解除时间\",extract(epoch FROM (release_time - start_time))/60 as \"处理时长\", responsible_name as \"人员\"\r\n  from andon.error_log where tag_type_sub_name='quality_error' and to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')"
    }
   ]
  }
 ]
}