{
 "title": "在制工单",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "line",
    "label": "虚拟线别",
    "query": "select  b.name_cn from work_order.virtual_line_current_log a,work_order.virtual_line b where a.virtual_line_id=b.id"
   }
  ]
 },
 "panels": [
  {
   "title": "当前生产工单",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \nb.work_order\nfrom work_order.virtual_line_current_log a,work_order.wo_config b,work_order.virtual_line c\nwhere a.wo_config_id=b.id and a.virtual_line_id=c.id and c.name_cn='$line'\norder by a.start_time\nlimit 1"
    }
   ]
  },
  {
   "title": "当前生产机种",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \nb.part_num\nfrom work_order.virtual_line_current_log a,work_order.wo_config b,work_order.virtual_line c\nwhere a.wo_config_id=b.id and a.virtual_line_id=c.id and c.name_cn='$line'\norder by a.start_time\nlimit 1"
    }
   ]
  },
  {
   "title": "各站位C/T",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "s" }
   ],
   "targets": [
    {
     "rawSql": "select \nd.name_cn as metric,a.cycle_time as value,now() as time\nfrom work_order.wo_machine_current_log a,work_order.wo_machine b,work_order.virtual_line c,common.machine d\nwhere a.machine_id=b.machine_id and b.machine_id=d.id and c.id=b.virtual_line_id and c.name_cn='$line'"
    }
   ]
  },
  {
   "title": "工单生产率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select productivity*100.0 from work_order.virtual_line_current_log a,work_order.virtual_line b\nwhere a.virtual_line_id=b.id and b.name_cn='$line'\norder by a.start_time limit 1"
    }
   ]
  },
  {
   "title": "生产数量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select a.quantity from work_order.virtual_line_current_log a,work_order.virtual_line b\nwhere a.virtual_line_id=b.id and b.name_cn='$line'\norder by a.start_time limit 1"
    }
   ]
  },
  {
   "title": "平衡率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select a.balance_rate*100 from work_order.virtual_line_current_log a,work_order.virtual_line b\nwhere a.virtual_line_id=b.id and b.name_cn='$line'\norder by a.start_time limit 1"
    }
   ]
  },
  {
   "title": "标准数量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select a.standard_num from work_order.wo_config a,\n(select a.wo_config_id,a.quantity from work_order.virtual_line_current_log a,work_order.virtual_line b\nwhere a.virtual_line_id=b.id and b.name_cn='$line'\norder by a.start_time limit 1) res\nwhere a.id=res.wo_config_id"
    }
   ]
  },
  {
   "title": "设备生产进度详情",
   "type": "advantech-datatable-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select d.name_cn as \"设备名称\",a.productivity*100 as \"生产率\",a.quantity as \"生产数量\",\nextract(epoch from now()-a.start_time)/60.0 as \"投入时间\",a.standard_time as \"标准工时\",\ne.standard_num*a.standard_time/60.0-extract(epoch from now()-a.start_time)/60.0 as \"剩余完成时间\"\nfrom work_order.wo_machine_current_log a,work_order.wo_machine b,work_order.virtual_line c,common.machine d,work_order.wo_config e\nwhere a.machine_id=b.machine_id and b.machine_id=d.id and c.id=b.virtual_line_id and a.wo_config_id=e.id and c.id=e.virtual_line_id and c.name_cn='$line'"
    }
   ]
  },
  {
   "title": "各站单片产品花费时长",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "s" }
   ],
   "targets": [
    {
     "rawSql": "select \nd.name_cn as metric,a.cycle_time_average as value,now() as time\nfrom work_order.wo_machine_current_log a,work_order.wo_machine b,work_order.virtual_line c,common.machine d\nwhere a.machine_id=b.machine_id and b.machine_id=d.id and c.id=b.virtual_line_id and c.name_cn='$line'"
    }
   ]
  }
 ]
}