{
 "title": "异常总览",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5m",
 "panels": [
  {
   "title": "各异常时间占比(%)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT sum(cost_time) as value,now() as time,'设备工治具异常' as metric\nfrom andon.error_log\nwhere tag_type_sub_name='equipment_error' and to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')"
    },
    {
     "rawSql": "SELECT sum(cost_time) as value,now() as time,'物料呼叫' as metric\nfrom andon.material_request_info\nwhere  to_char(createtime,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')"
    },
    {
     "rawSql": "SELECT sum(cost_time) as value,now() as time,'品质异常' as metric\nfrom andon.error_log\nwhere tag_type_sub_name='quality_error' and to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "异常时间汇总",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT (SELECT sum(cast(cost_time/60 as numeric(8,2))) as value\nfrom andon.material_request_info \nwhere to_char(createtime,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd'))+\n(SELECT sum(cast(cost_time/60 as numeric(8,2))) as value\nfrom andon.error_log \nwhere to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd'))"
    }
   ]
  },
  {
   "title": "物料呼叫信息",
   "type": "advantech-datatable-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT  machine_name as \"站位\",\r\n  to_char(createtime,'yyyy-MM-dd hh24:mi:ss') as \"触发时间\",to_char(take_time,'yyyy-MM-dd hh24:mi:ss') as \"送料时间\",cast(cost_time/60 as numeric(8,2)) ||' min' as \"处理时长\", take_person_name as \"人员\"\r\n  from andon.material_request_info where to_char(createtime,'yyyy-MM-dd')>=to_char(now()+'-7 day','yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "设备/工治具异常",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(cast(cost_time/60 as numeric(8,2))) as value,now() as time,'设备工治具异常' as metric\nfrom andon.error_log\nwhere tag_type_sub_name='equipment_error' and to_char(start_time,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "物料呼叫",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(cast(cost_time/60 as numeric(8,2))) as value,now() as time,'物料呼叫' as metric\nfrom andon.material_request_info\nwhere to_char(createtime,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "品质异常",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(cast(cost_time/60 as numeric(8,2))) as value,now() as time,'品质呼叫' as metric\nfrom andon.error_log\nwhere tag_type_sub_name='quality_error' and to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "设备/工治具异常信息",
   "type": "advantech-datatable-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT error_type_detail_name as \"异常信息\",machine_name as \"站位\", \r\n  to_char(start_time,'yyyy-MM-dd hh24:mi:ss') as \"触发时间\",to_char(release_time,'yyyy-MM-dd hh24:mi:ss') as \"解除时间\",cast(cost_time/60 as numeric(8,2)) ||' min' as \"处理时长\", responsible_name as \"人员\"\r\n  from andon.error_log where tag_type_sub_name='equipment_error' and to_char(start_time,'yyyy-MM-dd')>=to_char(now()+'-7 day','yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "品质异常信息",
   "type": "advantech-datatable-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT error_type_detail_name as \"异常信息\",machine_name as \"站位\",\r\n  to_char(start_time,'yyyy-MM-dd hh24:mi:ss') as \"触发时间\",to_char(release_time,'yyyy-MM-dd hh24:mi:ss') as \"解除时间\",cast(cost_time/60 as numeric(8,2)) as \"处理时长\", responsible_name as \"人员\"\r\n  from andon.error_log where tag_type_sub_name='quality_error' and to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')"
    }
   ]
  }
 ]
}