{
 "title": "当日进度",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "line",
    "label": "虚拟线别",
    "query": "select  name_cn from work_order.virtual_line"
   }
  ]
 },
 "panels": [
  {
   "title": "当前工单机种信息",
   "type": "advantech-machineinfo-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT (SELECT \nb.work_order\nfrom work_order.virtual_line_current_log a,work_order.wo_config b,work_order.virtual_line c\nwhere a.wo_config_id=b.id and a.virtual_line_id=c.id and c.name_cn='$line'\norder by a.start_time\nlimit 1) as \"工单\",\n(SELECT \nb.part_num\nfrom work_order.virtual_line_current_log a,work_order.wo_config b,work_order.virtual_line c\nwhere a.wo_config_id=b.id and a.virtual_line_id=c.id and c.name_cn='$line'\norder by a.start_time\nlimit 1) as \"机种\",\nto_char((select extract(epoch FROM (start_time - end_time))*1.0/60 as value  from \n(select a.end_time from work_order.virtual_line_log a order by start_time desc limit 1) res0,\n(select a.wo_config_id,a.start_time from work_order.virtual_line_current_log a,work_order.virtual_line b\nwhere a.virtual_line_id=b.id and b.name_cn='$line'\norder by a.start_time limit 1) res) ,'99D9') || 'Min' as \"换线时间\""
    }
   ]
  },
  {
   "title": "平衡率",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select a.balance_rate*100 from work_order.virtual_line_current_log a,work_order.virtual_line b\nwhere a.virtual_line_id=b.id and b.name_cn='$line'\norder by a.start_time limit 1"
    }
   ]
  },
  {
   "title": "工单生产率",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select productivity*100 from work_order.virtual_line_current_log a,work_order.virtual_line b\nwhere a.virtual_line_id=b.id and b.name_cn='$line'\norder by a.start_time limit 1"
    }
   ]
  },
  {
   "title": "生产数量",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select a.quantity from work_order.virtual_line_current_log a,work_order.virtual_line b\nwhere a.virtual_line_id=b.id and b.name_cn='$line'\norder by a.start_time limit 1"
    }
   ]
  },
  {
   "title": "标准数量",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select a.standard_num from work_order.wo_config a,\n(select a.wo_config_id,a.quantity from work_order.virtual_line_current_log a,work_order.virtual_line b\nwhere a.virtual_line_id=b.id and b.name_cn='$line'\norder by a.start_time limit 1) res\nwhere a.id=res.wo_config_id"
    }
   ]
  },
  {
   "title": "当日已完成工单",
   "type": "advantech-datatable-panel",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT c.work_order as \"工单\",c.part_num as \"料号\",c.standard_num as \"标准数量\",\nto_char(b.start_time,'yyyy-MM-dd hh24:mi:ss') as \"开始时间\",to_char(b.end_time,'yyyy-MM-dd hh24:mi:ss') as \"结束时间\",\nb.balance_rate as \"平衡率\",productivity as \"生产率\"\nfrom work_order.virtual_line a,work_order.virtual_line_log b,work_order.wo_config c\nwhere a.id=b.virtual_line_id and a.name_cn='$line' and c.id=b.wo_config_id \nand to_char(b.start_time,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd')\n\n"
    }
   ]
  }
 ]
}