{
 "title": "生产效能分析",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "生产总览",
   "type": "advantech-datatable-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT '工单完成数量' as \"参数\",\n(select sum(count) as value from work_order.work_order_log \nwhere extract(year from now())=year and month=1) as \"1月\",\n(select sum(count) as value from work_order.work_order_log \nwhere extract(year from now())=year and month=2) as \"2月\",\n(select sum(count) as value from work_order.work_order_log \nwhere extract(year from now())=year and month=3) as \"3月\",\n(select sum(count) as value from work_order.work_order_log \nwhere extract(year from now())=year and month=4) as \"4月\",\n(select sum(count) as value from work_order.work_order_log \nwhere extract(year from now())=year and month=5) as \"5月\",\n(select sum(count) as value from work_order.work_order_log \nwhere extract(year from now())=year and month=6) as \"6月\",\n(select sum(count) as value from work_order.work_order_log \nwhere extract(year from now())=year and month=7) as \"7月\",\n(select sum(count) as value from work_order.work_order_log \nwhere extract(year from now())=year and month=8) as \"8月\",\n(select sum(count) as value from work_order.work_order_log \nwhere extract(year from now())=year and month=9) as \"9月\",\n(select sum(count) as value from work_order.work_order_log \nwhere extract(year from now())=year and month=10) as \"10月\",\n(select sum(count) as value from work_order.work_order_log \nwhere extract(year from now())=year and month=11) as \"11月\",\n(select sum(count) as value from work_order.work_order_log \nwhere extract(year from now())=year and month=12) as \"12月\"\n"
    },
    {
     "rawSql": "select '标准产能' as \"参数\",\n(select sum(capacity) as value from work_order.capacity_config \nwhere extract(year from date)=extract(year from now()) and extract(month from date)=1) as \"1月\",\n(select sum(capacity) as value from work_order.capacity_config \nwhere extract(year from date)=extract(year from now()) and extract(month from date)=2) as \"2月\",\n(select sum(capacity) as value from work_order.capacity_config \nwhere extract(year from date)=extract(year from now()) and extract(month from date)=3) as \"3月\",\n(select sum(capacity) as value from work_order.capacity_config \nwhere extract(year from date)=extract(year from now()) and extract(month from date)=4) as \"4月\",\n(select sum(capacity) as value from work_order.capacity_config \nwhere extract(year from date)=extract(year from now()) and extract(month from date)=5) as \"5月\",\n(select sum(capacity) as value from work_order.capacity_config \nwhere extract(year from date)=extract(year from now()) and extract(month from date)=6) as \"6月\",\n(select sum(capacity) as value from work_order.capacity_config \nwhere extract(year from date)=extract(year from now()) and extract(month from date)=7) as \"7月\",\n(select sum(capacity) as value from work_order.capacity_config \nwhere extract(year from date)=extract(year from now()) and extract(month from date)=8) as \"8月\",\n(select sum(capacity) as value from work_order.capacity_config \nwhere extract(year from date)=extract(year from now()) and extract(month from date)=9) as \"9月\",\n(select sum(capacity) as value from work_order.capacity_config \nwhere extract(year from date)=extract(year from now()) and extract(month from date)=10) as \"10月\",\n(select sum(capacity) as value from work_order.capacity_config \nwhere extract(year from date)=extract(year from now()) and extract(month from date)=11) as \"11月\",\n(select sum(capacity) as value from work_order.capacity_config \nwhere extract(year from date)=extract(year from now()) and extract(month from date)=12) as \"12月\"\n"
    },
    {
     "rawSql": "select '实际产能' as \"参数\",\n(select sum(count) as value from work_order.capacity_log \nwhere extract(year from now())=year and month=1) as \"1月\",\n(select sum(count) as value from work_order.capacity_log \nwhere extract(year from now())=year and month=2) as \"2月\",\n(select sum(count) as value from work_order.capacity_log \nwhere extract(year from now())=year and month=3) as \"3月\",\n(select sum(count) as value from work_order.capacity_log \nwhere extract(year from now())=year and month=4) as \"4月\",\n(select sum(count) as value from work_order.capacity_log \nwhere extract(year from now())=year and month=5) as \"5月\",\n(select sum(count) as value from work_order.capacity_log \nwhere extract(year from now())=year and month=6) as \"6月\",\n(select sum(count) as value from work_order.capacity_log \nwhere extract(year from now())=year and month=7) as \"7月\",\n(select sum(count) as value from work_order.capacity_log \nwhere extract(year from now())=year and month=8) as \"8月\",\n(select sum(count) as value from work_order.capacity_log \nwhere extract(year from now())=year and month=1) as \"1月\",\n(select sum(count) as value from work_order.capacity_log \nwhere extract(year from now())=year and month=9) as \"9月\",\n(select sum(count) as value from work_order.capacity_log \nwhere extract(year from now())=year and month=10) as \"10月\",\n(select sum(count) as value from work_order.capacity_log \nwhere extract(year from now())=year and month=11) as \"11月\",\n(select sum(count) as value from work_order.capacity_log \nwhere extract(year from now())=year and month=12) as \"12月\"\n"
    }
   ]
  },
  {
   "title": "本月工单完成数量趋势",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "device": "select device",
     "plugin": "select plugin",
     "rawSql": "SELECT count as value,date as time,'工单数量' as metric from work_order.work_order_log\norder by date\n",
     "sensor": "select sensor",
     "tsType": "ts",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "本月产能趋势",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT count as value,date as time,'产能' as metric from work_order.capacity_log\norder by date"
    }
   ]
  }
 ]
}