{
 "title": "设备历史状态管理",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "群组",
    "query": "SELECT  b.name_cn  FROM common.area_layer a ,common.area_node b where  a.name_cn = '群组'  and  a.id = b.area_layer_id"
   },
   {
    "name": "area",
    "label": "城市",
    "query": "SELECT  name_cn  FROM common.area_node  where  upper_id =( SELECT  id FROM common.area_node where name_cn = '$group')"
   }
  ]
 },
 "panels": [
  {
   "title": "站位1稼动率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT a.utilization_rate*100\nfrom oee.utilization_rate_day a\nwhere to_char(a.insert_time,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd') and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 0) "
    }
   ]
  },
  {
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "device": "select device",
     "plugin": "select plugin",
     "rawSql": "select \r\n(case a.status_name\r\nwhen 'Run' then 1\r\nwhen 'Error' then 3\r\nwhen 'Idle' then 0\r\nwhen 'Off' then 2\r\nelse 6 end) as value,a.insert_time as time\r\nfrom oee.tricolor_tag_duration a\r\nwhere a.machine_id =(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 0) \r\nand to_char(a.insert_time::timestamp,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd') \r\norder by a.insert_time",
     "sensor": "select sensor",
     "tsType": "ts",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "站位2稼动率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT a.utilization_rate*100\nfrom oee.utilization_rate_day a\nwhere to_char(a.insert_time,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd') and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 1) "
    }
   ]
  },
  {
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 6 },
   "targets": [
    {
     "device": "select device",
     "plugin": "select plugin",
     "rawSql": "select \r\n(case a.status_name\r\nwhen 'Run' then 1\r\nwhen 'Error' then 3\r\nwhen 'Idle' then 0\r\nwhen 'Off' then 2\r\nelse 6 end) as value,a.insert_time as time\r\nfrom oee.tricolor_tag_duration a\r\nwhere a.machine_id =(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 1) \r\nand to_char(a.insert_time::timestamp,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd') \r\norder by a.insert_time",
     "sensor": "select sensor",
     "tsType": "ts",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "站位3稼动率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT a.utilization_rate*100\nfrom oee.utilization_rate_day a\nwhere to_char(a.insert_time,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd') and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 2) "
    }
   ]
  },
  {
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 12 },
   "targets": [
    {
     "device": "select device",
     "plugin": "select plugin",
     "rawSql": "select \r\n(case a.status_name\r\nwhen 'Run' then 1\r\nwhen 'Error' then 3\r\nwhen 'Idle' then 0\r\nwhen 'Off' then 2\r\nelse 6 end) as value,a.insert_time as time\r\nfrom oee.tricolor_tag_duration a\r\nwhere a.machine_id =(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 3) \r\nand to_char(a.insert_time::timestamp+'8 hour','yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd') \r\norder by a.insert_time",
     "sensor": "select sensor",
     "tsType": "ts",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "站位4稼动率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT a.utilization_rate*100\nfrom oee.utilization_rate_day a\nwhere to_char(a.insert_time,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd') and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 3) "
    }
   ]
  },
  {
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 18 },
   "targets": [
    {
     "device": "select device",
     "plugin": "select plugin",
     "rawSql": "select \r\n(case a.status_name\r\nwhen 'Run' then 1\r\nwhen 'Error' then 3\r\nwhen 'Idle' then 0\r\nwhen 'Off' then 2\r\nelse 6 end) as value,a.insert_time as time\r\nfrom oee.tricolor_tag_duration a\r\nwhere a.machine_id =(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 2) \r\nand to_char(a.insert_time::timestamp+'8 hour','yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd') \r\norder by a.insert_time",
     "sensor": "select sensor",
     "tsType": "ts",
     "type": "timeserie"
    }
   ]
  }
 ]
}