{
 "title": "设备故障统计",
 "time": { "from": "2020-04-08T04:42:56.674Z", "to": "2020-04-20T17:53:14.089Z" },
 "panels": [
  { "title": "设备故障统计", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 0, "y": 0 }, "content": "# title" },
  {
   "title": "本月设备故障明细",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT machine_name as \"故障设备\",to_char(start_time::timestamp,'yyyy-MM-dd hh24:mi:ss') as \"开始时间\",\n(case when release_time<'2001-01-01' then '-' else to_char(release_time::timestamp,'yyyy-MM-dd hh24:mi:ss') end) as \"结束时间\",\ncast(cast(cost_time/60 as numeric(8,2)) as varchar)||' min' as \"故障时长\"\nfrom andon.error_log\nwhere to_char(start_time,'yyyy-MM')=to_char(now(),'yyyy-MM')\norder by start_time desc"
    }
   ]
  },
  {
   "title": "本日累计故障次数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(*)\nfrom andon.error_log\nwhere to_char(start_time,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "本日累计故障时长",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(cast(cost_time/60 as numeric(8,2)))\nfrom andon.error_log\nwhere to_char(start_time,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "本周累计故障次数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(*)\nfrom andon.error_log\nwhere to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "本周累计故障时长",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(cast(cost_time/60 as numeric(8,2)))\nfrom andon.error_log\nwhere to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "本月累计故障次数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(*)\nfrom andon.error_log\nwhere to_char(start_time,'yyyy-MM')=to_char(now(),'yyyy-MM')"
    }
   ]
  },
  {
   "title": "本月累计故障时长",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(cast(cost_time/60 as numeric(8,2)))\nfrom andon.error_log\nwhere to_char(start_time,'yyyy-MM')=to_char(now(),'yyyy-MM')"
    }
   ]
  },
  {
   "title": "设备故障次数",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select count(mytime) as value,to_date(mytime,'yyyy-MM-dd')::timestamp+'-8 hour' as time,'次数' as metirc from \n(select machine_name,to_char(start_time,'yyyy-MM-dd') as mytime\nfrom andon.error_log\nwhere to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-1 month','yyyy-MM-dd')) res\ngroup by mytime\norder by mytime\n"
    }
   ]
  },
  {
   "title": "设备故障时间",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select sum(cost_time) as value,to_date(mytime,'yyyy-MM-dd')::timestamp as time,'故障停机时间' as metirc from \n(select machine_name,cost_time,to_char(start_time,'yyyy-MM-dd') as mytime\nfrom andon.error_log\nwhere to_char(start_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-1 month','yyyy-MM-dd')) res\ngroup by mytime\norder by mytime"
    }
   ]
  }
 ]
}