{
 "title": "设备时间稼动率分析",
 "description": "按照天",
 "time": { "from": "now/w", "to": "now/w" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "群组",
    "query": "SELECT  b.name_cn  FROM common.area_layer a ,common.area_node b where  a.name_cn = '群组'  and  a.id = b.area_layer_id"
   },
   {
    "name": "area",
    "label": "城市",
    "query": "SELECT  name_cn  FROM common.area_node  where  upper_id =( SELECT  id FROM common.area_node where name_cn = '$group')"
   }
  ]
 },
 "panels": [
  {
   "title": "站位1",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT a.utilization_rate*100\nfrom oee.utilization_rate_day a,common.machine b\nwhere to_char(a.insert_time,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd') and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 0) "
    }
   ]
  },
  {
   "title": "设备状态",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n(case a.status_name\nwhen 'Run' then 1\nwhen 'Error' then 3\nwhen 'Idle' then 0\nwhen 'Off' then 2\nelse 6 end) as status\nfrom oee.tricolor_tag_status a,common.machine b\nwhere  a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 0) \norder by a.insert_time desc\nlimit 1"
    }
   ]
  },
  {
   "title": "状态统计",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "select '运行' as \"状态\",cast(CAST(duration_time as DECIMAL(13,2)) as varchar)||' min' as \"累计时间\"\r\nfrom oee.tag_time_day \r\nwhere machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 0)  and status_name='Run'  and \r\nto_char(date,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd')\r\nunion all\r\nselect '异常' as \"状态\",cast(CAST(duration_time as DECIMAL(13,2)) as varchar)||' min' as \"累计时间\"\r\nfrom oee.tag_time_day \r\nwhere machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 0)  and status_name='Error'  and \r\nto_char(date,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd')\r\nunion all\r\nselect '待机' as \"状态\",cast(CAST(duration_time as DECIMAL(13,2)) as varchar)||' min' as \"累计时间\"\r\nfrom oee.tag_time_day \r\nwhere machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 0)  and status_name='Idle'  and \r\nto_char(date,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd')\r\nunion all\r\nselect '停机' as \"状态\",cast(CAST(duration_time as DECIMAL(13,2)) as varchar)||' min' as \"累计时间\"\r\nfrom oee.tag_time_day \r\nwhere machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 0)  and status_name='Off'  and \r\nto_char(date,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "各状态时间趋势",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select '运行时间' as metric,b.duration_time as value,b.date as time\r\nfrom oee.tag_time_day b\r\nwhere  b.machine_id= (SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 0)  and b.status_name='Run'  and \r\nto_char(b.date,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')\r\norder by b.date"
    },
    {
     "rawSql": "select '异常时间' as metric,b.duration_time as value,b.date as time\r\nfrom oee.tag_time_day b\r\nwhere  b.machine_id= (SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 0)  and b.status_name='Error'  and \r\nto_char(b.date,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')\r\norder by b.date"
    },
    {
     "rawSql": "select '待机时间' as metric,b.duration_time as value,b.date as time\r\nfrom oee.tag_time_day b\r\nwhere  b.machine_id= (SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 0)  and b.status_name='Idel'  and \r\nto_char(b.date,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')\r\norder by b.date"
    },
    {
     "rawSql": "select '停机时间' as metric,b.duration_time as value,b.date as time\nfrom oee.tag_time_day b\nwhere  b.machine_id= (SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 0)  and b.status_name='Off'  and \nto_char(b.date,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')\norder by b.date\n"
    }
   ]
  },
  {
   "title": "稼动率趋势",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select '稼动率' as metric,a.utilization_rate*100 as value,a.insert_time::timestamp as time\nfrom oee.utilization_rate_day a\nwhere a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 0)   and \nto_char(a.insert_time,'yyyy-MM-dd')>=to_char(now()+'-7 day','yyyy-MM-dd')\norder by a.insert_time"
    }
   ]
  },
  {
   "title": "持续时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT a.duration_time\nfrom oee.tricolor_tag_duration a,common.machine b\nwhere to_char(a.insert_time,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd') and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 0) \norder by a.insert_time desc\nlimit 1"
    }
   ]
  },
  {
   "title": "站位2",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT a.utilization_rate*100\nfrom oee.utilization_rate_day a\nwhere to_char(a.insert_time,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd') and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 1) "
    }
   ]
  },
  {
   "title": "设备状态",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n(case a.status_name\nwhen 'Run' then 1\nwhen 'Error' then 3\nwhen 'Idle' then 0\nwhen 'Off' then 2\nelse 6 end) as status\nfrom oee.tricolor_tag_status a,common.machine b\nwhere  a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 1) \norder by a.insert_time desc\nlimit 1"
    }
   ]
  },
  {
   "title": "状态统计",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 6 },
   "targets": [
    {
     "rawSql": "select '运行' as \"状态\",cast(CAST(duration_time as DECIMAL(13,2)) as varchar)||' min' as \"累计时间\"\r\nfrom oee.tag_time_day \r\nwhere machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 1)  and status_name='Run'  and \r\nto_char(date,'yyyy-MM-dd')>=to_char(now(),'yyyy-MM-dd')\r\nunion all\r\nselect '异常' as \"状态\",cast(CAST(duration_time as DECIMAL(13,2)) as varchar)||' min' as \"累计时间\"\r\nfrom oee.tag_time_day \r\nwhere machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 1)  and status_name='Error'  and \r\nto_char(date,'yyyy-MM-dd')>=to_char(now(),'yyyy-MM-dd')\r\nunion all\r\nselect '待机' as \"状态\",cast(CAST(duration_time as DECIMAL(13,2)) as varchar)||' min' as \"累计时间\"\r\nfrom oee.tag_time_day \r\nwhere machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 1)  and status_name='Idle'  and \r\nto_char(date,'yyyy-MM-dd')>=to_char(now(),'yyyy-MM-dd')\r\nunion all\r\nselect '停机' as \"状态\",cast(CAST(duration_time as DECIMAL(13,2)) as varchar)||' min' as \"累计时间\"\r\nfrom oee.tag_time_day \r\nwhere machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 1)  and status_name='Off'  and \r\nto_char(date,'yyyy-MM-dd')>=to_char(now(),'yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "各状态时间趋势",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select '运行时间' as metric,b.duration_time as value,b.date as time\r\nfrom oee.tag_time_day b\r\nwhere  b.machine_id= (SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 1)  and b.status_name='Run'  and \r\nto_char(b.date,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')\r\norder by b.date"
    },
    {
     "rawSql": "select '异常时间' as metric,b.duration_time as value,b.date as time\r\nfrom oee.tag_time_day b\r\nwhere  b.machine_id= (SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 1)  and b.status_name='Error'  and \r\nto_char(b.date,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')\r\norder by b.date"
    },
    {
     "rawSql": "select '待机时间' as metric,b.duration_time as value,b.date as time\r\nfrom oee.tag_time_day b\r\nwhere  b.machine_id= (SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 1)  and b.status_name='Idel'  and \r\nto_char(b.date,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')\r\norder by b.date"
    },
    {
     "rawSql": "select '停机时间' as metric,b.duration_time as value,b.date as time\r\nfrom oee.tag_time_day b\r\nwhere  b.machine_id= (SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 1)  and b.status_name='Off'  and \r\nto_char(b.date,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')\r\norder by b.date "
    }
   ]
  },
  {
   "title": "稼动率趋势",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select '稼动率' as metric,a.utilization_rate*100 as value,a.insert_time::timestamp as time\nfrom oee.utilization_rate_day a,common.machine c\nwhere a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 1) and \nto_char(a.insert_time,'yyyy-MM-dd')>=to_char(now()+'-7 day','yyyy-MM-dd')\norder by a.insert_time"
    }
   ]
  },
  {
   "title": "持续时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT a.duration_time\nfrom oee.tricolor_tag_duration a\nwhere to_char(a.insert_time,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd') and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 1)\norder by a.insert_time desc\nlimit 1"
    }
   ]
  },
  {
   "title": "站位3",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT a.utilization_rate*100\nfrom oee.utilization_rate_day a\nwhere to_char(a.insert_time,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd') and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 2)"
    }
   ]
  },
  {
   "title": "设备状态",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n(case a.status_name\nwhen 'Run' then 1\nwhen 'Error' then 3\nwhen 'Idle' then 0\nwhen 'Off' then 2\nelse 6 end) as status\nfrom oee.tricolor_tag_status a\nwhere  a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 2)  \norder by a.insert_time desc\nlimit 1"
    }
   ]
  },
  {
   "title": "状态统计",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 12 },
   "targets": [
    {
     "rawSql": "select '运行' as \"状态\",cast(CAST(duration_time as DECIMAL(13,2)) as varchar)||' min' as \"累计时间\"\r\nfrom oee.tag_time_day \r\nwhere machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 2)  and status_name='Run'  and \r\nto_char(date,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd')\r\nunion all\r\nselect '异常' as \"状态\",cast(CAST(duration_time as DECIMAL(13,2)) as varchar)||' min' as \"累计时间\"\r\nfrom oee.tag_time_day \r\nwhere machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 2)  and status_name='Error'  and \r\nto_char(date,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd')\r\nunion all\r\nselect '待机' as \"状态\",cast(CAST(duration_time as DECIMAL(13,2)) as varchar)||' min' as \"累计时间\"\r\nfrom oee.tag_time_day \r\nwhere machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 2)  and status_name='Idle'  and \r\nto_char(date,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd')\r\nunion all\r\nselect '停机' as \"状态\",cast(CAST(duration_time as DECIMAL(13,2)) as varchar)||' min' as \"累计时间\"\r\nfrom oee.tag_time_day \r\nwhere machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 2)  and status_name='Off'  and \r\nto_char(date,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "各状态时间趋势",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select '运行时间' as metric,b.duration_time as value,a.insert_time::timestamp+'8 hour' as time\nfrom oee.utilization_rate_day a,oee.status_duration_day b\nwhere a.id=b.upper_id and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 2)  and b.status_name='Run'  and \nto_char(a.insert_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')\norder by a.insert_time"
    },
    {
     "rawSql": "select '异常时间' as metric,b.duration_time as value,a.insert_time::timestamp+'8 hour' as time\nfrom oee.utilization_rate_day a,oee.status_duration_day b\nwhere a.id=b.upper_id and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 2) and b.status_name='Error'  and \nto_char(a.insert_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')\norder by a.insert_time"
    },
    {
     "rawSql": "select '待机时间' as metric,b.duration_time as value,a.insert_time::timestamp+'8 hour' as time\nfrom oee.utilization_rate_day a,oee.status_duration_day b,common.machine c\nwhere a.id=b.upper_id and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 2) and b.status_name='Idle'  and \nto_char(a.insert_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')\norder by a.insert_time"
    },
    {
     "rawSql": "select '停机时间' as metric,b.duration_time as value,a.insert_time::timestamp+'8 hour' as time\nfrom oee.utilization_rate_day a,oee.status_duration_day b,common.machine c\nwhere a.id=b.upper_id and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 2) and b.status_name='Off'  and \nto_char(a.insert_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')\norder by a.insert_time\n"
    }
   ]
  },
  {
   "title": "稼动率趋势",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select '稼动率' as metric,a.utilization_rate*100 as value,a.insert_time::timestamp as time\nfrom oee.utilization_rate_day a\nwhere a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 2)   and \nto_char(a.insert_time,'yyyy-MM-dd')>=to_char(now()::timestamp +'-7 day','yyyy-MM-dd')\norder by a.insert_time"
    }
   ]
  },
  {
   "title": "持续时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT a.duration_time\nfrom oee.tricolor_tag_duration a\nwhere to_char(a.insert_time,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd') and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 2)\norder by a.insert_time desc\nlimit 1"
    }
   ]
  },
  {
   "title": "站位4",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT a.utilization_rate*100\nfrom oee.utilization_rate_day a,common.machine b\nwhere to_char(a.insert_time,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd') and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 3) "
    }
   ]
  },
  {
   "title": "设备状态",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n(case a.status_name\nwhen 'Run' then 1\nwhen 'Error' then 3\nwhen 'Idle' then 0\nwhen 'Off' then 2\nelse 6 end) as status\nfrom oee.tricolor_tag_status a\nwhere  a.machine_id= (SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 3)\norder by a.insert_time desc\nlimit 1"
    }
   ]
  },
  {
   "title": "状态统计",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 18 },
   "targets": [
    {
     "rawSql": "select '运行' as \"状态\",cast(CAST(duration_time as DECIMAL(13,2)) as varchar)||' min' as \"累计时间\"\r\nfrom oee.tag_time_day \r\nwhere machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 3)  and status_name='Run'  and \r\nto_char(date,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd')\r\nunion all\r\nselect '异常' as \"状态\",cast(CAST(duration_time as DECIMAL(13,2)) as varchar)||' min' as \"累计时间\"\r\nfrom oee.tag_time_day \r\nwhere machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 3)  and status_name='Error'  and \r\nto_char(date,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd')\r\nunion all\r\nselect '待机' as \"状态\",cast(CAST(duration_time as DECIMAL(13,2)) as varchar)||' min' as \"累计时间\"\r\nfrom oee.tag_time_day \r\nwhere machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 3)  and status_name='Idle'  and \r\nto_char(date,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd')\r\nunion all\r\nselect '停机' as \"状态\",cast(CAST(duration_time as DECIMAL(13,2)) as varchar)||' min' as \"累计时间\"\r\nfrom oee.tag_time_day \r\nwhere machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 3)  and status_name='Off'  and \r\nto_char(date,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd')"
    }
   ]
  },
  {
   "title": "各状态时间趋势",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select '运行时间' as metric,b.duration_time as value,a.insert_time::timestamp+'8 hour' as time\nfrom oee.utilization_rate_day a,oee.status_duration_day b\nwhere a.id=b.upper_id and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 3)  and b.status_name='Run'  and \nto_char(a.insert_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')\norder by a.insert_time"
    },
    {
     "rawSql": "select '异常时间' as metric,b.duration_time as value,a.insert_time::timestamp+'8 hour' as time\nfrom oee.utilization_rate_day a,oee.status_duration_day b\nwhere a.id=b.upper_id and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 3) and b.status_name='Error'  and \nto_char(a.insert_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')\norder by a.insert_time"
    },
    {
     "rawSql": "select '待机时间' as metric,b.duration_time as value,a.insert_time::timestamp+'8 hour' as time\nfrom oee.utilization_rate_day a,oee.status_duration_day b,common.machine c\nwhere a.id=b.upper_id and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 3) and b.status_name='Idle'  and \nto_char(a.insert_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')\norder by a.insert_time"
    },
    {
     "rawSql": "select '停机时间' as metric,b.duration_time as value,a.insert_time::timestamp+'8 hour' as time\nfrom oee.utilization_rate_day a,oee.status_duration_day b,common.machine c\nwhere a.id=b.upper_id and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 3) and b.status_name='Off'  and \nto_char(a.insert_time,'yyyy-MM-dd')>=to_char(now()::timestamp+'-7 day','yyyy-MM-dd')\norder by a.insert_time\n"
    }
   ]
  },
  {
   "title": "稼动率趋势",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select '稼动率' as metric,a.utilization_rate*100 as value,a.insert_time::timestamp as time\nfrom oee.utilization_rate_day a\nwhere a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 3)   and \nto_char(a.insert_time,'yyyy-MM-dd')>=to_char(now()::timestamp +'-7 day','yyyy-MM-dd')\norder by a.insert_time"
    }
   ]
  },
  {
   "title": "持续时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT a.duration_time\nfrom oee.tricolor_tag_duration a\nwhere to_char(a.insert_time,'yyyy-MM-dd')=to_char(now(),'yyyy-MM-dd') and a.machine_id=(SELECT id from common.machine where area_node_id = (SELECT id from common.area_node where name_cn = '$area') order by id asc limit 1 offset 3)\norder by a.insert_time desc\nlimit 1"
    }
   ]
  }
 ]
}